map f1 new_tab_with_cwd lazygit
// map f2 new_tab_with_cwd broot
// map f3 new_tab_with_cwd k9s
map f4 new_tab_with_cwd 

map ctrl+shift+g show_last_command_output

map super+h previous_tab
map super+l next_tab

modify_font underline_position 25

font_family IosevkaTerm Nerd Font Mono

modify_font underline_position 25

font_family IosevkaTerm Nerd Font Mono
// font_family FiraCode Nerd Font Mono
// font_family JetBrains Mono
// font_family ComicShannsMono Nerd Font
font_size 20
disable_ligatures cursor
background_opacity 1
shell_integration disabled
# repaint_delay 4
# input_delay 3
cursor_shape block
confirm_os_window_close 0
cursor #f0f0f0
cursor_text_color #ffffff
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
scrollback_lines 5000
url_color #0f0f0f
url_style single
sync_to_monitor yes
enable_audio_bell no

# window_padding_width 0
window_padding_width 5

// include ./current-theme.conf
// include ./everforest.conf
// include ./github-theme.conf
// include ./gruv.conf
// include ./monokai-pro.conf

# border on gnome + wayland
# linux_display_server x11

# This file is auto-generated by shipwright.nvim
# vim:ft=kitty
## name: kanagawabones
## author: Michael Chris Lopez
## license: MIT
## upstream: https://github.com/mcchrish/zenbones.nvim/raw/main/extras/kitty/kanagawabones.conf
## blurb: A zenbones variant inspired by Kanagawa.
foreground                      #DDD8BB
background                      #1F1F28
selection_foreground            #DDD8BB
selection_background            #49473E
# Cursor colors
cursor                          #E6E0C2
cursor_text_color               #1F1F28
# URL underline color when hovering with mouse
# kitty window border colors
# OS Window titlebar colors
# Tab bar colors
active_tab_foreground           #DDD8BB
active_tab_background           #614A82
inactive_tab_foreground         #DDD8BB
inactive_tab_background         #363644
# Colors for marks (marked text in the terminal)
# The basic 16 colors
# black
color0 #1F1F28
color8 #3C3C51
# red
color1 #E46A78
color9 #EC818C
# green
color2  #98BC6D
color10 #9EC967
# yellow
color3  #E5C283
color11 #F1C982
# blue
color4  #7EB3C9
color12 #7BC2DF
# magenta
color5  #957FB8
color13 #A98FD2
# cyan
color6  #7EB3C9
color14 #7BC2DF
# white
color7  #DDD8BB
color15 #A8A48D
# You can set the remaining 240 colors as color16 to color255.

