map f1 new_tab_with_cwd lazygit
// map f2 new_tab_with_cwd broot
// map f3 new_tab_with_cwd k9s
map f4 new_tab_with_cwd 

map ctrl+shift+g show_last_command_output

map super+h previous_tab
map super+l next_tab

modify_font underline_position 25

// font_family IosevkaTerm Nerd Font Mono
// font_family FiraCode Nerd Font Mono
// font_family JetBrains Mono
font_family ComicShannsMono Nerd Font
font_size 17 
disable_ligatures cursor
background_opacity 1
shell_integration disabled
# repaint_delay 4
# input_delay 3
cursor_shape block
confirm_os_window_close 0
cursor #f0f0f0
cursor_text_color #ffffff
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
scrollback_lines 5000
url_color #0f0f0f
url_style single
sync_to_monitor yes
enable_audio_bell no

# window_padding_width 0
window_padding_width 5

// include ./current-theme.conf
// include ./everforest.conf
// include ./github-theme.conf
// include ./gruv.conf
// include ./monokai-pro.conf

// border on gnome + wayla20
// linux_display_server x11


# vscode dark color scheme for Kitty
# By https://github/mofiqul

foreground            #d4d4d4
background            #1e1e1e
selection_foreground  #1e1e1e
selection_background  #d7ba7d
url_color             #0087BD

# black
color0   #1e1e1e
color8   #808080

# red
color1   #f44747
color9   #f44747

# green
color2   #608b4e
color10  #608b4e

# yellow
color3   #dcdcaa
color11  #dcdcaa

# blue
color4  #569cd6
color12 #569cd6

# magenta
color5   #c678dd
color13  #c678dd

# cyan
color6   #56b6c2
color14  #56b6c2

# white
color7   #d4d4d4
color15  #d4d4d4


