theme = "github_dark"

[editor]
cursorline = true
line-number = "relative"
idle-timeout = 0
completion-replace = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
# display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

[editor.statusline]
left = ["mode", "spinner"]
center = ["version-control", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
