# ┌──────┐
# │ misc │
# └──────┘

font_family	Iosevka Nerd Font
# font_family	SF Mono
font_size 18
disable_ligatures cursor
scrollback_lines 5000
# repaint_delay 10
# input_delay 3
sync_to_monitor yes
enable_audio_bell no
remember_window_size no
window_padding_width 5
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# ┌────────┐
# │ colors │
# └────────┘
#
background_opacity 1
# background_opacity 0.95
shell_integration disabled
cursor_shape block

confirm_os_window_close 0

# tab_bar_min_tabs            1
# tab_bar_edge                bottom
# tab_bar_style               powerline
# tab_powerline_style         slanted
# tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

cursor #f0f0f0
cursor_text_color #ffffff
cursor_shape block

cursor_blink_interval 0.5
cursor_stop_blinking_after 0

scrollback_lines 5000

url_color #0f0f0f
url_style single

# repaint_delay 10
# input_delay 3

sync_to_monitor yes

enable_audio_bell no

remember_window_size no

window_padding_width 20.0
background            #1e1e2e

# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
