font_family	Iosevka Nerd Font
font_size 18
disable_ligatures cursor
background_opacity 1
shell_integration disabled
repaint_delay 6
cursor_shape block
confirm_os_window_close 0
cursor #f0f0f0
cursor_text_color #ffffff
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
scrollback_lines 5000
url_color #0f0f0f
url_style single
sync_to_monitor yes
enable_audio_bell no
remember_window_size no
window_padding_width 15.0
include current-theme.conf
# background #0f0f0f
# background #181825
background #11111b

linux_display_server x1
