-- local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
--
-- local workspace_dir = '/home/nils/tmp/' .. project_name
--
-- local config = {
--     cmd = { 'jdt-language-server', '-configuration /home/nils//.cache/jdtls/config', '-data /home/nils//.cache/jdtls/workspace' },
--     -- root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- require('jdtls').start_or_attach(config)
