-- -- deps:
-- require("img-clip").setup({
-- 	-- use recommended settings from above
-- })
-- require("copilot").setup({
-- 	-- use recommended settings from above
-- })
-- require("render-markdown").setup({
-- 	-- use recommended settings from above
-- })
-- require("avante_lib").load()
-- require("avante").setup({
-- 	-- Your config here!
-- 	provider = "copilot",
-- 	auto_suggestions_provider = "copilot",
-- })
