-- require("lualine").setup({
-- 	options = {
-- 		theme = "catppuccin",
-- 		-- ... the rest of your lualine config
-- 		component_separators = { left = "", right = "" },
-- 		section_separators = { left = "", right = "" },
--         disabled_filetypes = {
--             "dapui_scopes",
--             "dapui_breakpoints",
--             "dapui_watches",
--             "dapui_stacks",
--             "dapui_console",
--             "dap-repl"
--         }
-- 	},
-- 	sections = {
-- 		lualine_a = { "mode" },
-- 		lualine_b = { "branch", "diff", "diagnostics" },
-- 		lualine_c = { "filename" },
-- 		lualine_x = { "filetype" },
-- 		lualine_y = { "progress" },
-- 		lualine_z = { "location" },
-- 	},
-- })
