-- require('neorg').setup {
--     load = {
--         ["core.defaults"] = {},          -- Loads default behaviour
--         ["core.concealer"] = {},         -- Adds pretty icons to your documents
--         ["core.export"] = {},         -- Adds pretty icons to your documents
--         ["core.completion"] = {
--             config = {
--                 engine = "nvim-cmp",
--             },
--         },         -- Adds pretty icons to your documents
--         ["core.dirman"] = {              -- Manages Neorg workspaces
--             config = {
--                 workspaces = {
--                     notes = "~/notes",
--                 },
--             },
--         },
--     },
-- }
