# theme = "catppuccin_mocha"
theme = "custom_theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
cursorline = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
# display-inl"always-hints = true

[editor.file-picker]
hidden = false
