# theme = "catppuccin_mocha"
theme = "github_dark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.lsp]
# display-inl"always-hints = true

[editor.file-picker]
hidden = false
