{ pkgs, lib, ... }:
let
  token =
    lib.strings.removeSuffix "\n" (builtins.readFile /home/nils/factorio-token);
  factorio = pkgs.factorio.override {
    username = "nilsdev";
    token = token;
  };
in
{
  fonts.packages = with pkgs; [
    cantarell-fonts
    iosevka
    fira-code
    jetbrains-mono
    comic-mono
    nerdfonts
    fantasque-sans-mono
  ];

  nixpkgs.config.permittedInsecurePackages = [ "electron-25.9.0" ];

  users.users.nils.packages = with pkgs; [
    tuxedo-rs
    discord
    factorio
    ollama
    asciinema
    zoxide
    eza
    zellij
    air
    newsflash
    anki-bin
    argocd
    bluetuith
    bottles
    brave
    brightnessctl
    bun
    gnome.polari
    gnomeExtensions.auto-move-windows
    gnomeExtensions.just-perfection
    gnomeExtensions.impatience
    gnome-extension-manager
    gnome.gnome-tweaks
    cfssl
    choose
    powertop
    cilium-cli
    delve
    gnome.dconf-editor
    dig
    direnv
    du-dust
    dwl
    feh
    ffmpeg
    ffmpeg
    file
    firefox
    fzf
    gammastep
    gcc
    ginkgo
    wmctrl
    git
    # tangram
    glibc
    brotab
    gnumake
    go
    go-callvis
    golangci-lint
    google-chrome
    gopls
    goreleaser
    gradience
    grim
    grml-zsh-config
    kustomize
    helix
    htop
    imagemagick
    jc
    jdk21
    jellyfin-media-player
    jq
    k6
    k9s
    keyd
    kind
    kitty
    krew
    kubebuilder
    kubectl
    kubectx
    kubernetes-helm
    kubeseal
    kubeshark
    lazydocker
    lazygit
    libnotify
    libqalculate
    qalculate-gtk
    liquidctl
    localsend
    ltex-ls
    lua-language-server
    # mako
    dunst
    marksman
    mpv
    nil
    nixfmt
    nixpkgs-fmt
    nodePackages.js-beautify
    nodePackages_latest.bash-language-server
    nodePackages_latest.prettier
    nodePackages_latest.pyright
    nodePackages_latest.stylelint
    nodePackages_latest.svelte-language-server
    nodePackages_latest.typescript-language-server
    nodePackages_latest.vscode-langservers-extracted
    vscode-fhs
    nodePackages_latest.yaml-language-server
    nodejs
    obs-studio
    obsidian
    openssl
    openvpn
    pandoc
    pavucontrol
    popeye
    poppler_utils
    python3
    python311Packages.python-lsp-server
    ranger
    ripgrep
    ruff-lsp
    shell_gpt
    shellcheck
    signal-desktop
    slurp
    somebar
    stylua
    swappy
    swaybg
    tailwindcss
    tailwindcss-language-server
    tmux
    tree
    unrar-wrapper
    unzip
    vial
    waybar
    wezterm
    wl-clipboard
    wtype
    xdg-desktop-portal-gtk
    xdg-desktop-portal-hyprland
    xdg-utils
    yt-dlp
    zathura
    zsh-syntax-highlighting
  ];
}
