{ pkgs, ... }: {
  fonts.packages = with pkgs; [
    cantarell-fonts
    iosevka
    fira-code
    jetbrains-mono
    comic-mono
    nerdfonts
    fantasque-sans-mono
  ];

  nixpkgs.config.permittedInsecurePackages = [ "electron-25.9.0" ];

  users.users.nils.packages = with pkgs; [
    zoxide
    eza
    air
    anki-bin
    argocd
    bluetuith
    bottles
    brave
    brightnessctl
    bun
    cfssl
    choose
    cilium-cli
    delve
    dig
    direnv
    du-dust
    dwl
    feh
    ffmpeg
    ffmpeg
    file
    firefox
    fzf
    gammastep
    gcc
    ginkgo
    git
    glibc
    gnumake
    go
    go-callvis
    golangci-lint
    google-chrome
    gopls
    goreleaser
    gradience
    grim
    grml-zsh-config
    helix
    htop
    imagemagick
    jc
    jdk21
    jellyfin-media-player
    jq
    k6
    k9s
    keyd
    kind
    kitty
    krew
    kubebuilder
    kubectl
    kubectx
    kubernetes-helm
    kubeseal
    kubeshark
    lazydocker
    lazygit
    libnotify
    libqalculate
    liquidctl
    localsend
    ltex-ls
    lua-language-server
    mako
    marksman
    mpv
    nil
    nixfmt
    nodePackages.js-beautify
    nodePackages_latest.bash-language-server
    nodePackages_latest.prettier
    nodePackages_latest.pyright
    nodePackages_latest.stylelint
    nodePackages_latest.svelte-language-server
    nodePackages_latest.typescript-language-server
    nodePackages_latest.vscode-langservers-extracted
    vscode-fhs
    nodePackages_latest.yaml-language-server
    nodejs
    obs-studio
    obsidian
    openssl
    openvpn
    pandoc
    pavucontrol
    popeye
    poppler_utils
    python3
    python311Packages.python-lsp-server
    ranger
    ripgrep
    ruff-lsp
    shell_gpt
    shellcheck
    signal-desktop
    slurp
    somebar
    stylua
    swappy
    swaybg
    tailwindcss
    tailwindcss-language-server
    tmux
    tree
    unrar-wrapper
    unzip
    vial
    waybar
    wezterm
    wl-clipboard
    wtype
    xdg-desktop-portal-gtk
    xdg-desktop-portal-hyprland
    xdg-utils
    yt-dlp
    zathura
    zsh-syntax-highlighting
  ];
}
