update:
	cowsay "please fix home manager tarball pull so we can use pure mode" || echo "no cow :("
	sudo nixos-rebuild switch --flake '.#'$$(hostname) --impure

switch-desktop:
	cowsay "please fix home manager tarball pull so we can use pure mode" || echo "no cow :("
	sudo nixos-rebuild switch --flake '.#desktop' --impure

switch-laptop:
	cowsay "please fix home manager tarball pull so we can use pure mode" || echo "no cow :("
	sudo nixos-rebuild switch --flake '.#laptop' --impure
