{ pkgs, ... }: {
  users.users.nils.packages = with pkgs; [
    (python310.withPackages (ps:
      with ps; [
        python310Packages.bpython
        python310Packages.diagrams
        python310Packages.jupyter_client
        python310Packages.pillow
        python310Packages.pynvim
        python310Packages.python-lsp-server
        python310Packages.recipe-scrapers
      ]))
    act
    adw-gtk3
    ansible
    asciinema
    bat
    bluetuith
    bottles
    brightnessctl
    broot
    cilium-cli
    clang-tools
    clang-tools
    clusterctl
    containerlab
    deja-dup
    delve
    dig
    direnv
    discord
    distrobox
    docker
    docker-compose
    dolphin-emu
    du-dust
    etcd
    fd
    feh
    ffmpeg
    firefox
    fzf
    gammastep
    gaphor
    gcc
    ginkgo
    git
    gitlab-runner
    gitleaks
    glow
    gnome.adwaita-icon-theme
    gnome.eog
    gnome.gnome-clocks
    gnome.gnome-disk-utility
    gnome.gnome-font-viewer
    gnome.nautilus
    gnome.simple-scan
    gnumake
    go
    go-tools
    golangci-lint
    gomodifytags
    gopls
    gore
    gotests
    gotools
    gping
    gradience
    grim
    grml-zsh-config
    helix
    html-tidy
    hubble
    imlib2Full
    jdt-language-server
    jellyfin-media-player
    jq
    k3d
    k3sup
    k9s
    kind
    kitty
    kubectl
    kubectx
    kubernetes-helm
    kubeseal
    lazydocker
    lazygit
    libnotify
    libqalculate
    libwebp
    liquidctl
    litecli
    lm_sensors
    ltex-ls
    ltrace
    lua-language-server
    lua-language-server
    luarocks
    mako
    marksman
    masscan
    minikube
    mission-center
    mpv
    nil
    nixfmt
    nixpkgs-fmt
    nixpkgs-fmt
    nmap
    nnn
    nodePackages.js-beautify
    nodePackages_latest.bash-language-server
    nodePackages_latest.bash-language-server
    nodePackages_latest.prettier
    nodePackages_latest.prettier
    nodePackages_latest.pyright
    nodePackages_latest.stylelint
    nodePackages_latest.svelte-language-server
    nodePackages_latest.typescript-language-server
    nodePackages_latest.vscode-langservers-extracted
    nodePackages_latest.yaml-language-server
    nodejs
    obs-studio
    obsidian
    openvpn
    pandoc
    pavucontrol
    pciutils
    popeye
    prismlauncher
    radare2
    radeontop
    ranger
    rclone
    ripgrep
    rsync
    rust-analyzer
    ryujinx
    shellcheck
    signal-desktop
    slurp
    speedtest-cli
    sqlite
    sshfs
    steam
    swappy
    swaybg
    syncthing
    taplo
    terraform
    terraform-ls
    texlab
    texlive.combined.scheme-medium
    tmux
    traceroute
    tree
    typescript
    typst
    typst-fmt
    typst-lsp
    ueberzug
    ueberzugpp
    unrar-wrapper
    unzip
    usbutils
    via # somehow doesnt work, appimage in repo works on arch tho
    virt-manager
    virtualenv
    vscode.fhs
    websocat
    wine
    wl-clipboard
    wtype
    xdg-desktop-portal-hyprland
    xdg-utils
    yamlfmt
    yarn
    yt-dlp
    ytfzf
    yuzu-early-access
    zathura
    zoxide
    zsh-syntax-highlighting
  ];
}
