theme = "custom_theme"


[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", "insert_mode"]
"C-r" = ":config-reload"
"H" = ":buffer-previous"
"L" = ":buffer-next"

[keys.normal."ü"]
"f" = "goto_prev_function"
"d" = "goto_prev_diag"
"t" = "goto_prev_class"
"e" = "goto_prev_parameter"

[keys.normal."+"]
"f" = "goto_next_function"
"d" = "goto_next_diag"
"t" = "goto_next_class"
"e" = "goto_next_parameter"

[keys.normal.tab]
"p" = ":sh live-markdown-preview"
"s" = ["move_next_word_end", "move_prev_word_start", "surround_add"]
"a" = ["select_regex", "align_selections"]
"m" = ":pipe /home/nils/dotfiles/scripts/helix-align-markdown-table.py"

[editor]
idle-timeout = 0
line-number = "relative"
bufferline = "multiple"
rulers = [80]
text-width = 80
mouse = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
# wrap-at-text-width = true
max-indent-retain = 0

[editor.lsp]
# display-inlay-hints	= true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
