# theme = "github_dark"
theme = "kanagawa"

[keys.normal]
# C-y = "toggle_copilot_auto"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

"H" = ":buffer-previous"
"L" = ":buffer-next"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", "insert_mode"]
"C-r" = ":reload-all"
"C-q" = ":bc"

# [keys.insert]
# "C-k" = "show_or_next_copilot_completion"
# "C-j" = "hide_or_prev_copilot_completion"
# "tab" = "apply_copilot_completion"

[keys.normal.tab]
"s" = ["move_next_word_end", "move_prev_word_start", "surround_add"]
"a" = ["select_regex", "align_selections"]
"m" = ":pipe /home/nils/dotfiles/scripts/helix-align-markdown-table.py"

[editor]
idle-timeout = 0
true-color = true
line-number = "relative"
bufferline = "multiple"
rulers = [80]
text-width = 80
mouse = false
scrolloff = 10 

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[editor.indent-guides]
# render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
# wrap-at-text-width = true
max-indent-retain = 0

[editor.lsp]
# display-inlay-hints	= true 
# display-messages = true
# copilot-auto = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
