theme = "custom_theme"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", "insert_mode"]
"C-r" = ":config-reload"
"C-h" = ":buffer-previous"
"C-l" = ":buffer-next"

[keys.normal.tab]
"h" = ":buffer-previous"
"l" = ":buffer-next"
"s" = ["move_next_word_end", "move_prev_word_start", "surround_add"]
"a" = ["select_regex", "align_selections"]

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
text-width = 80
mouse = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
# wrap-at-text-width = true
max-indent-retain = 0

[editor.lsp]
# display-inlay-hints	= true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
